### ISSUE TITLE
关于mAP的变化

### ISSUE THREAD

**Issue by yfyang16** [Muxv/OICR-pytorch#1]
Hi, 想问下OICR 的 mAP随着Epoch数的增加大概是如何变化的？我在前9个epoch只缓慢上升到1%。
然后我用的roi是edgebox生成的，不知能否share一下你的roi文件？谢谢

**Comment by Muxv** [comment]
项目有点久了，文件已经丢失了，实在不好意思
当时selective_search和edge_box生成的roi都有使用，我的代码的Dataset部分存在bug，roi的读取上存在一定问题，当时没有即时上传到github
正常情况下mAP会上升的很快的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Muxv/OICR-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月15日(星期二) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Muxv/OICR-pytorch] 关于mAP的变化 (#1)





 
Hi, 想问下OICR 的 mAP随着Epoch数的增加大概是如何变化的？我在前9个epoch只缓慢上升到1%。
 然后我用的roi是edgebox生成的，不知能否share一下你的roi文件？谢谢

**Comment by yfyang16** [comment]
ok好的，谢谢！
